package datamodel;

/*
 * @author      Vasilis Poulos <address @ cse42805@cs.uoi.gr>
 * @version     0.1         
 */


/*
 * 	PatternComponent class that defines the basic methods of the composite
 *	structure, along with default TRIVIAL IMPLEMENTATIONS.
 *	   | 	@author Vasilis Poulos
 *	   |	think this means: define methods, some may do nothing and thats 
 *	   | 	because we need child classes to inherit them 
 *	
 *	Random notes on packages:
 * 
 * 	CreatePackage-Compile  	javac -d . demo.java
 *	Run						java mypack.demo
 */

import java.util.Scanner; // may not needed - only for testing


public class PatternComponent implements Cloneable
{
	protected String name;

	public PatternComponent (String name)
    {
        this.name = name;
    }

	/**
	 *
	 */
	public void add(PatternComponent component){}

	/**
	 *
	 */
	public void remove(){}
	
	/**
	 * Creates a clone of a PatternComponent object.
     *     This is a Deep copy of this object because name is of type
     *     String which is immutable.
     *
     * I think it is best to use copy constructors or factory methods
     * instead of overriding clone().
     *
     * @return PatternComponent clone.
	 */
	@Override
	public PatternComponent clone()
	{
		try
		{
			return (PatternComponent) super.clone();
		}
		catch(CloneNotSupportedException e)
		{
			throw new AssertionError();
		}
	}

	/**
	 *	Saves a new name
	 *  
	 *	@param	outputStream	generated by Scanner [?]
	 *	@since	0.1
	 */
	public void saveName(String name)
	{
		this.name = name;
	}
	
	/**
	 *
	 */
	public void saveContents() {}

	/**
	 *	Only for testing
	 *  
	 *	@param	outputStream	generated by Scanner [?]
	 *	@return	components name
	 *	@since	0.1
	 */
	public String getName()
	{
		return this.name;
	}
}